version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: feedback_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-feedback}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5442:5432"
    networks:
      - feedback_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feedback_api
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - feedback_network
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"

networks:
  feedback_network:
    driver: bridge

volumes:
  postgres_data: